
# version: '3'
services:

  # app:
  #   image: 'jc21/nginx-proxy-manager:latest'
  #   restart: unless-stopped
  #   ports:
  #     - '80:80'
  #     - '81:81'
  #     - '443:443'
  #   volumes:
  #     - ./data:/data
  #     - ./letsencrypt:/etc/letsencrypt
    
  ui_react:
    container_name: ui_react
    build:
      context: ./ui_react
    ports:
      - "6000:6000"
    networks:
      - rent_room_network
    environment:
      - NODE_ENV=production

  api_node:
    container_name: api_node
    build:
      context: ./api_node
    ports:
      - "9000:9000"
    networks:
      - rent_room_network
    environment:
      - NODE_ENV=production

 
    # depends_on:
    #   - react-app
    #   - node-app

networks:
  rent_room_network:
    driver: bridge











# version: '3.8'

# name: mern-app

# services:
#   # app:
#   #   image: 'jc21/nginx-proxy-manager:latest'
#   #   restart: unless-stopped
#   #   ports:
#   #     - '80:80'
#   #     - '81:81'
#   #     - '443:443'
#   #   volumes:
#   #     - ./data:/data
#   #     - ./letsencrypt:/etc/letsencrypt


#   backend:
#     build:
#       context: ./node260724
#       dockerfile: Dockerfile
#     restart: unless-stopped
#     volumes:
#       - ./node260724:/app
#       - /app/node_modules
#     networks:
#       - mern-app
#     ports:
#       - 8000:8000
  

#   frontend:
#     build:
#       context: ./react260724
#       dockerfile: Dockerfile
#     restart: unless-stopped
#     networks:
#       - mern-app
#     ports:
#       - 3000:3000
#     command: npm start

# # networks:
# #   mern-app:
# #     driver: bridge











# # version: '3.8'
# # services:
# #   app:
# #     build:
# #       context: ./fr
# #     ports:
# #       - "3000:80"
# #     volumes:
# #       - ./fr:/app
# #     working_dir: /app
# #     command: ["npm", "start"]
